name: CI

on: push

jobs:

  install:
    name: Install
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - name: Install dependencies
      run: npm install

  lint:
    name: Lint
    needs: [install]
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - name: Run lint
      run: npm run lint